version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: kcauth-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kcauth
      MYSQL_USER: kcauth
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0
    container_name: kcauth-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: quay.io/minio/minio
    entrypoint: sh
    command: -c "minio server /data --console-address ':9001' & sleep 5 && /usr/bin/minio-init.sh && tail -f /dev/null"
    container_name: minio
    # networks:
    #   kcserver:
    restart: always
    environment:
      TZ: Asia/Shanghai
      MINIO_ROOT_USER: kcserver
      MINIO_ROOT_PASSWORD: kcai1212
      MINIO_REGION: zhuhai-1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - minio_data:/data
      - ./minio-init.sh:/usr/bin/minio-init.sh
    ports:
      - "9002:9000" # 测试用
      - "9003:9001"

  kcauth-server:
    image: kcaitech/auth:latest
    container_name: kcauth-server
    restart: always
    volumes:
      - ./config.yaml:/app/config/config.yaml
    ports:
      - "8080:80"
      - "8081:81"

volumes:
  mysql_data:
  redis_data:
  minio_data: