source_db:
  host: localhost
  port: 3806
  user: root
  password: kKEIjksvnOOIjdZ6rtzE
  database: kcserver

target_db:
  host: localhost
  port: 3306
  user: root
  password: password
  database: kcauth 